export const QUERY_KEYS = {
  USER: ["user"] as const,
  MARKERS: ["markers"] as const,
  PLACE_TYPE_COUNTS: ["place_type_counts"] as const,
  OWNED_MARKERS: (userId: string) => ["owned_markers", userId] as const,
  PUB_LIST: "pub_list" as const,
  PLACE: (id: string) => ["place", id] as const,
  OWNED_PLACES: ["owned_places"] as const,
  USER_REVIEWS: (userId: string) => ["user_reviews", userId] as const,
  USER_REQUESTS: (userId: string) => ["user_requests", userId] as const,
  REQUESTS: ["requests"] as const,
  ADMIN_COUNTS: ["admin_counts"] as const,
  RECENT_REQUESTS: ["recent_requests"] as const,
  PLACE_REQUESTS: ["place_requests"] as const,
  OWNER_CLAIMS: ["owner_claims"] as const,
  USERS: ["users"] as const,
  OWNER_STATS: ["owner_stats"] as const,
  OWNER_RECENT_COMMENTS: ["owner_recent_comments"] as const,
  OWNER_CHART_DATA: ["owner_chart_data"] as const,
  OWNER_RATING_BREAKDOWN: ["owner_rating_breakdown"] as const,
} as const;
